### ISSUE TITLE
port file path wrong on unix

### ISSUE THREAD

**Issue by hkiel** [OpenModelica/OMJulia#1]
The ZMQ port file is built using the user name in unixoid systems. See OpenModelica/OMMatlab#1

**Comment by arun3688** [comment]
@hkiel  You mean the file path is wrong in Julia  and not read ?, so it must be changed to format similar to OMMatlab like you did, Also i have not tested in Unix platforms, So does the OMMatlab works for you in MAc ?

**Comment by hkiel** [comment]
OMMatlab works as expected with my fix. I suspect OMJulia to not work as is for the same reason.
BTW, I had to call `javaaddpath('jeromq-0.4.4-SNAPSHOT.jar')` within Matlab to make it find ZMQ.

**Comment by arun3688** [comment]
OMJulia port file fixed, regarding OMMatlab, See the comment
